version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Use the appropriate Node.js version
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync build/ s3://lazarus-portfolio --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id E2MT3FZ9IUIVCN --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: build
